# Generated by Django 5.1.7 on 2026-08-14 01:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, default='')),
                ('stackable', models.BooleanField(default=False)),
                ('equip_slot', models.CharField(blank=True, choices=[('helmet', 'Helmet'), ('arrows', 'Arrows'), ('gloves', 'Gloves'), ('body', 'Body'), ('legs', 'Legs'), ('boots', 'Boots'), ('ring', 'Ring')], max_length=16, null=True)),
                ('color', models.CharField(default='#c4a574', max_length=7)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=32)),
                ('x', models.PositiveIntegerField(default=12)),
                ('y', models.PositiveIntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InventorySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_index', models.PositiveSmallIntegerField()),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='game.item')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_slots', to='game.player')),
            ],
            options={
                'ordering': ['slot_index'],
                'unique_together': {('player', 'slot_index')},
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(choices=[('helmet', 'Helmet'), ('arrows', 'Arrows'), ('gloves', 'Gloves'), ('body', 'Body'), ('legs', 'Legs'), ('boots', 'Boots'), ('ring', 'Ring')], max_length=16)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='game.item')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='game.player')),
            ],
            options={
                'ordering': ['slot'],
                'unique_together': {('player', 'slot')},
            },
        ),
        migrations.CreateModel(
            name='PlayerSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('attack', 'Attack'), ('defense', 'Defense'), ('strength', 'Strength'), ('hits', 'Hits'), ('ranged', 'Ranged'), ('prayer', 'Prayer'), ('magic', 'Magic'), ('cooking', 'Cooking'), ('woodcutting', 'Woodcutting'), ('fletching', 'Fletching'), ('fishing', 'Fishing'), ('firemaking', 'Firemaking'), ('crafting', 'Crafting'), ('smithing', 'Smithing'), ('mining', 'Mining'), ('herblaw', 'Herblaw'), ('agility', 'Agility'), ('thieving', 'Thieving')], max_length=32)),
                ('xp', models.PositiveIntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='game.player')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('player', 'name')},
            },
        ),
    ]
