# Generated by Django 5.1.7

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0003_item_sprite"),
    ]

    operations = [
        migrations.CreateModel(
            name="SceneryKind",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("rsc_id", models.PositiveIntegerField(unique=True)),
                ("name", models.CharField(max_length=64)),
                ("description", models.TextField(blank=True, default="")),
                ("commands", models.JSONField(blank=True, default=list)),
                ("model_name", models.CharField(blank=True, default="", max_length=64)),
                ("width", models.PositiveSmallIntegerField(default=1)),
                ("height", models.PositiveSmallIntegerField(default=1)),
                ("block_type", models.CharField(default="unblocked", max_length=16)),
                ("item_height", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["rsc_id"],
            },
        ),
        migrations.CreateModel(
            name="Scenery",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("x", models.PositiveIntegerField()),
                ("y", models.PositiveIntegerField()),
                ("direction", models.PositiveSmallIntegerField(default=0)),
                (
                    "kind",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placements",
                        to="game.scenerykind",
                    ),
                ),
            ],
            options={
                "ordering": ["y", "x", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="scenery",
            index=models.Index(fields=["x", "y"], name="game_scener_x_y_idx"),
        ),
    ]
