# Generated by Django 5.1.7 on 2026-10-01 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_playerskill_current_level'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='scenery',
            new_name='game_scener_x_4fc881_idx',
            old_name='game_scener_x_y_idx',
        ),
    ]
