from .models import EquipmentSlot

# Catalog of items. `sprite` is a PNG in frontend/public/sprites/rsc/items/.
ITEMS = [
    {
        "key": "bronze_helmet",
        "name": "Bronze Helmet",
        "description": "A battered bronze helmet.",
        "equip_slot": EquipmentSlot.HELMET,
        "color": "#b87333",
        "sprite": "104-medium_bronze_helmet.png",
    },
    {
        "key": "leather_gloves",
        "name": "Leather Gloves",
        "description": "Soft leather gloves.",
        "equip_slot": EquipmentSlot.GLOVES,
        "color": "#8b5a2b",
        "sprite": "16-leather_gloves.png",
    },
    {
        "key": "leather_boots",
        "name": "Leather Boots",
        "description": "Comfortable walking boots.",
        "equip_slot": EquipmentSlot.BOOTS,
        "color": "#6b4423",
        "sprite": "17-boots.png",
    },
    {
        "key": "leather_body",
        "name": "Leather Body",
        "description": "A light leather cuirass.",
        "equip_slot": EquipmentSlot.BODY,
        "color": "#a0673b",
        "sprite": "15-leather_armour.png",
    },
    {
        "key": "leather_chaps",
        "name": "Leather Chaps",
        "description": "Leather leg armour.",
        "equip_slot": EquipmentSlot.LEGS,
        "color": "#8a5530",
        "sprite": "761-protective_trousers.png",
    },
    {
        "key": "gold_ring",
        "name": "Gold Ring",
        "description": "A plain gold ring.",
        "equip_slot": EquipmentSlot.RING,
        "color": "#ffd700",
        "sprite": "283-gold_ring.png",
    },
    {
        "key": "coins",
        "name": "Coins",
        "description": "Lovely shiny coins.",
        "equip_slot": None,
        "stackable": True,
        "color": "#e6c35c",
        "sprite": "10-coins.png",
    },
    {
        "key": "bronze_dagger",
        "name": "Bronze Dagger",
        "description": "A small bronze dagger.",
        "equip_slot": EquipmentSlot.WEAPON,
        "color": "#c08a4a",
        "sprite": "62-bronze_dagger.png",
    },
    {
        "key": "iron_dagger",
        "name": "Iron Dagger",
        "description": "A short iron dagger.",
        "equip_slot": EquipmentSlot.WEAPON,
        "color": "#9aa3ad",
        "sprite": "28-iron_dagger.png",
    },
    {
        "key": "bronze_sword",
        "name": "Bronze Sword",
        "description": "A short bronze sword.",
        "equip_slot": EquipmentSlot.WEAPON,
        "color": "#c08a4a",
        "sprite": "66-bronze_short_sword.png",
    },
    {
        "key": "iron_sword",
        "name": "Iron Sword",
        "description": "A serviceable iron sword.",
        "equip_slot": EquipmentSlot.WEAPON,
        "color": "#9aa3ad",
        "sprite": "1-iron_short_sword.png",
    },
    {
        "key": "steel_sword",
        "name": "Steel Sword",
        "description": "A well-forged steel sword.",
        "equip_slot": EquipmentSlot.WEAPON,
        "color": "#cfd6de",
        "sprite": "67-steel_short_sword.png",
    },
    {
        "key": "longsword",
        "name": "Longsword",
        "description": "A long steel blade.",
        "equip_slot": EquipmentSlot.WEAPON,
        "color": "#d8d3cc",
        "sprite": "72-steel_long_sword.png",
    },
    {
        "key": "scimitar",
        "name": "Scimitar",
        "description": "A curved slashing sword.",
        "equip_slot": EquipmentSlot.WEAPON,
        "color": "#e6c35c",
        "sprite": "84-steel_scimitar.png",
    },
    {
        "key": "bronze_axe",
        "name": "Bronze Axe",
        "description": "A double-headed bronze axe.",
        "equip_slot": EquipmentSlot.WEAPON,
        "color": "#b87333",
        "sprite": "87-bronze_axe.png",
    },
    {
        "key": "iron_battleaxe",
        "name": "Iron Battleaxe",
        "description": "A heavy iron battleaxe.",
        "equip_slot": EquipmentSlot.WEAPON,
        "color": "#6b7280",
        "sprite": "89-iron_battle_axe.png",
    },
    {
        "key": "steel_battleaxe",
        "name": "Steel Battleaxe",
        "description": "A vicious steel battleaxe.",
        "equip_slot": EquipmentSlot.WEAPON,
        "color": "#94a3b8",
        "sprite": "90-steel_battle_axe.png",
    },
    {
        "key": "bronze_mace",
        "name": "Bronze Mace",
        "description": "A bronze-headed mace.",
        "equip_slot": EquipmentSlot.WEAPON,
        "color": "#cd7f32",
        "sprite": "94-bronze_mace.png",
    },
    {
        "key": "iron_mace",
        "name": "Iron Mace",
        "description": "An iron mace, good for crushing.",
        "equip_slot": EquipmentSlot.WEAPON,
        "color": "#6e6a63",
        "sprite": "0-iron_mace.png",
    },
    {
        "key": "warhammer",
        "name": "Warhammer",
        "description": "A hefty warhammer.",
        "equip_slot": EquipmentSlot.WEAPON,
        "color": "#8a7a55",
        "sprite": "168-hammer.png",
    },
    {
        "key": "shortbow",
        "name": "Shortbow",
        "description": "A simple wooden shortbow.",
        "equip_slot": EquipmentSlot.WEAPON,
        "color": "#d7b07a",
        "sprite": "189-shortbow.png",
    },
    {
        "key": "longbow",
        "name": "Longbow",
        "description": "A tall wooden longbow.",
        "equip_slot": EquipmentSlot.WEAPON,
        "color": "#8c6b3d",
        "sprite": "188-longbow.png",
    },
    {
        "key": "bronze_arrows",
        "name": "Bronze Arrows",
        "description": "Arrows tipped with bronze.",
        "equip_slot": EquipmentSlot.ARROWS,
        "stackable": True,
        "color": "#cd7f32",
        "sprite": "11-bronze_arrows.png",
    },
    {
        "key": "iron_arrows",
        "name": "Iron Arrows",
        "description": "Arrows tipped with iron.",
        "equip_slot": EquipmentSlot.ARROWS,
        "stackable": True,
        "color": "#9aa3ad",
        "sprite": "638-iron_arrows.png",
    },
    {
        "key": "bronze_spear",
        "name": "Bronze Spear",
        "description": "A bronze-tipped spear.",
        "equip_slot": EquipmentSlot.WEAPON,
        "color": "#c08a4a",
        "sprite": "827-bronze_spear.png",
    },
    {
        "key": "halberd",
        "name": "Halberd",
        "description": "A long polearm with an axe head.",
        "equip_slot": EquipmentSlot.WEAPON,
        "color": "#6b7280",
        "sprite": "78-steel_2-handed_sword.png",
    },
    {
        "key": "wooden_shield",
        "name": "Wooden Shield",
        "description": "A wooden heater shield with iron studs.",
        "equip_slot": EquipmentSlot.SHIELD,
        "color": "#6b4423",
        "sprite": "4-wooden_shield.png",
    },
    {
        "key": "iron_square_shield",
        "name": "Iron Square Shield",
        "description": "A sturdy iron square shield.",
        "equip_slot": EquipmentSlot.SHIELD,
        "color": "#7b8794",
        "sprite": "3-iron_square_shield.png",
    },
    {
        "key": "kite_shield",
        "name": "Kite Shield",
        "description": "A tall kite shield.",
        "equip_slot": EquipmentSlot.SHIELD,
        "color": "#4b5563",
        "sprite": "2-iron_kite_shield.png",
    },
    {
        "key": "staff",
        "name": "Staff",
        "description": "A plain wooden staff.",
        "equip_slot": EquipmentSlot.WEAPON,
        "color": "#8c6b3d",
        "sprite": "100-staff.png",
    },
    {
        "key": "magic_staff",
        "name": "Magic Staff",
        "description": "A staff crowned with a dull crystal.",
        "equip_slot": EquipmentSlot.WEAPON,
        "color": "#c084fc",
        "sprite": "198-magic_staff.png",
    },
    {
        "key": "wand",
        "name": "Wand",
        "description": "A short magical wand.",
        "equip_slot": EquipmentSlot.WEAPON,
        "color": "#d4a84b",
        "sprite": "614-battlestaff.png",
    },
    {
        "key": "bronze_claws",
        "name": "Bronze Claws",
        "description": "A pair of bronze claw weapons.",
        "equip_slot": EquipmentSlot.WEAPON,
        "color": "#b87333",
        "sprite": "1076-bronze_throwing_knife.png",
    },
    {
        "key": "steel_claws",
        "name": "Steel Claws",
        "description": "A pair of steel claw weapons.",
        "equip_slot": EquipmentSlot.WEAPON,
        "color": "#9aa3ad",
        "sprite": "1077-steel_throwing_knife.png",
    },
]


# Scattered along Lumbridge Meadow's path and clearing.
GROUND_SPAWNS = [
    ("bronze_dagger", 14, 10, 1),
    ("iron_dagger", 10, 9, 1),
    ("bronze_sword", 16, 10, 1),
    ("iron_sword", 18, 10, 1),
    ("steel_sword", 20, 10, 1),
    ("longsword", 8, 10, 1),
    ("scimitar", 22, 10, 1),
    ("bronze_axe", 15, 8, 1),
    ("iron_battleaxe", 17, 8, 1),
    ("steel_battleaxe", 6, 10, 1),
    ("bronze_mace", 9, 11, 1),
    ("iron_mace", 11, 11, 1),
    ("warhammer", 19, 11, 1),
    ("shortbow", 7, 9, 1),
    ("longbow", 5, 10, 1),
    ("iron_arrows", 5, 11, 25),
    ("bronze_spear", 13, 8, 1),
    ("halberd", 21, 11, 1),
    ("wooden_shield", 14, 8, 1),
    ("iron_square_shield", 16, 8, 1),
    ("kite_shield", 4, 10, 1),
    ("staff", 23, 10, 1),
    ("magic_staff", 21, 9, 1),
    ("wand", 12, 8, 1),
    ("bronze_claws", 8, 11, 1),
    ("steel_claws", 10, 8, 1),
]
